### PR TITLE
initial commit: mongodb operator installation instructions

### PR DESCRIPTION
**Pull request by smukherjee16**
### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by rohitkshetty** [comment]
Did you have any images that needed to be added?

**Comment by smukherjee16** [comment]
[Mongo DB Operator Installation Steps.pdf](https://github.com/mongodb/mongodb-enterprise-kubernetes/files/5170641/Mongo.DB.Operator.Installation.Steps.pdf)

Attached the pdf with screenshots.

**Review by rohitkshetty — APPROVED** [review]

**Comment by rodrigovalin** [comment]
Hello @smukherjee16 thanks for contributing.

Can you please make sure you sign our [CLA](https://www.mongodb.com/legal/contributor-agreement).

I think you are missing some of the images in that PDF file in the patch. We already have some documentation in [here](https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/docs/openshift-marketplace.md) that you might want to base your changes on.

Please let me know if there's anything I can do to help.

**Comment by jamesbroadhead** [comment]
Thank you!

**Pull request closed without merging**
