### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by cmendible**
Cloud Manger should be Cloud Manager

### CODE REVIEW

**Comment by antonlisovenko** [comment]
Thanks @cmendible for the fix!

**Comment by jamesbroadhead** [comment]
Hi @cmendible  -

Could you please sign our CLA for this PR?
https://www.mongodb.com/legal/contributor-agreement

All the best,

James

**Comment by cmendible** [comment]
Hi @jamesbroadhead  just signed the agreement!

**Comment by jamesbroadhead** [comment]
@cmendible confirmed - thank you!

**Pull request merged**
